---
collections:
  - name: https://github.com/ephes/ops-library.git
    type: git
    version: 5faa07767dc83aa06501a09d2ed59a199b6d8ed5
  - name: community.postgresql
    version: 4.2.0
  - name: community.general
    version: 12.6.0
  - name: community.sops
    version: 2.3.0
  - name: ansible.posix
    version: 2.1.0
