---
collections:
  - name: https://github.com/ephes/ops-library.git
    type: git
    version: e92fb68ceec622d1f0fcdf07c040fba0ad6fb113
  - name: community.postgresql
    version: 4.2.0
  - name: community.general
    version: 12.6.0
  - name: community.sops
    version: 2.3.0
  - name: ansible.posix
    version: 2.1.0
