---
all:
  vars:
    ansible_connection: ssh
    ansible_user: root
  children:
    django_chat:
      children:
        staging:
          hosts:
            django-chat-staging:
              ansible_host: staging.djangochat.example.invalid
        production:
          hosts:
            django-chat-production:
              ansible_host: production.djangochat.example.invalid
