---
django_chat_environment: staging
django_chat_wagtail_fqdn: django-chat-staging.example.invalid
django_chat_traefik_host_rule: "Host(`{{ django_chat_wagtail_fqdn }}`)"
django_chat_django_allowed_hosts: "{{ django_chat_wagtail_fqdn }},localhost"

wagtail_fqdn: "{{ django_chat_wagtail_fqdn }}"
wagtail_traefik_host_rule: "{{ django_chat_traefik_host_rule }}"
wagtail_app_port: 10015
