# Generated by Django 6.0.4 on 2026-04-21 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cast', '0062_alter_transcript_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastSourceMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simplecast_podcast_id', models.CharField(max_length=64, unique=True)),
                ('rss_feed_url', models.URLField(max_length=1000)),
                ('simplecast_source_url', models.URLField(max_length=1000)),
                ('site_source_url', models.URLField(blank=True, max_length=1000)),
                ('website_url', models.URLField(blank=True, max_length=1000)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('source_title', models.CharField(max_length=255)),
                ('source_description', models.TextField(blank=True)),
                ('source_is_explicit', models.BooleanField(blank=True, null=True)),
                ('source_episode_count', models.PositiveIntegerField(blank=True, null=True)),
                ('source_published_at', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('first_imported_at', models.DateTimeField(auto_now_add=True)),
                ('last_imported_at', models.DateTimeField(auto_now=True)),
                ('podcast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='django_chat_source_metadata', to='cast.podcast')),
            ],
            options={
                'ordering': ['source_title'],
            },
        ),
        migrations.CreateModel(
            name='EpisodeSourceMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matching_key', models.CharField(max_length=512, unique=True)),
                ('rss_guid', models.CharField(blank=True, max_length=255)),
                ('simplecast_episode_id', models.CharField(blank=True, max_length=64)),
                ('simplecast_slug', models.SlugField(blank=True, max_length=255)),
                ('episode_number', models.PositiveIntegerField(blank=True, null=True)),
                ('source_title', models.CharField(max_length=255)),
                ('rss_source_url', models.URLField(blank=True, max_length=1000)),
                ('simplecast_source_url', models.URLField(blank=True, max_length=1000)),
                ('simplecast_api_url', models.URLField(blank=True, max_length=1000)),
                ('simplecast_episode_url', models.URLField(blank=True, max_length=1000)),
                ('original_rss_enclosure_url', models.URLField(blank=True, max_length=1000)),
                ('simplecast_enclosure_url', models.URLField(blank=True, max_length=1000)),
                ('simplecast_audio_file_url', models.URLField(blank=True, max_length=1000)),
                ('audio_file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('rss_description_html', models.TextField(blank=True)),
                ('rss_content_html', models.TextField(blank=True)),
                ('rss_is_explicit', models.BooleanField(blank=True, null=True)),
                ('simplecast_description', models.TextField(blank=True)),
                ('simplecast_long_description_html', models.TextField(blank=True)),
                ('simplecast_transcript_html', models.TextField(blank=True)),
                ('simplecast_is_explicit', models.BooleanField(blank=True, null=True)),
                ('source_published_at', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('first_imported_at', models.DateTimeField(auto_now_add=True)),
                ('last_imported_at', models.DateTimeField(auto_now=True)),
                ('episode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='django_chat_source_metadata', to='cast.episode')),
            ],
            options={
                'ordering': ['-source_published_at', '-episode_number', 'source_title'],
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(('rss_guid', ''), _negated=True),
                        fields=('rss_guid',),
                        name='imports_unique_episode_rss_guid',
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(('simplecast_episode_id', ''), _negated=True),
                        fields=('simplecast_episode_id',),
                        name='imports_unique_simplecast_episode_id',
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(('simplecast_slug', ''), _negated=True),
                        fields=('simplecast_slug',),
                        name='imports_unique_simplecast_slug',
                    ),
                ],
            },
        ),
    ]
