# Generated by Django 6.0.4 on 2026-04-22 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0062_alter_transcript_options'),
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeAudioImportMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=1000)),
                ('source_url_kind', models.CharField(max_length=64)),
                ('source_content_type', models.CharField(blank=True, max_length=255)),
                ('source_byte_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('copied_byte_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('storage_name', models.CharField(max_length=1000)),
                ('copied_at', models.DateTimeField()),
                ('first_imported_at', models.DateTimeField(auto_now_add=True)),
                ('last_imported_at', models.DateTimeField(auto_now=True)),
                ('audio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='django_chat_import_metadata', to='cast.audio')),
                ('episode_metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_import_metadata', to='imports.episodesourcemetadata')),
            ],
            options={
                'ordering': ['episode_metadata__source_title'],
            },
        ),
    ]
