# Generated by Django 6.0.4 on 2026-04-22 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_episodeaudioimportmetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastSourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=32)),
                ('source_id', models.CharField(blank=True, max_length=128)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('new_window', models.BooleanField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('channel_id', models.CharField(blank=True, max_length=128)),
                ('channel_name', models.CharField(blank=True, max_length=255)),
                ('first_imported_at', models.DateTimeField(auto_now_add=True)),
                ('last_imported_at', models.DateTimeField(auto_now=True)),
                ('podcast_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='imports.podcastsourcemetadata')),
            ],
            options={
                'ordering': ['podcast_metadata', 'location', 'display_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('podcast_metadata', 'source_key'), name='imports_unique_podcast_source_link')],
            },
        ),
    ]
